export enum identifierTypeEnum {
  name = "NAME",
  sourceId = "SOURCEID",
  systemId = "SYSTEMID",
  productId = "PRODUCTID",
  username = "USERNAME",
  accountId = "ACCOUNTID",
  emailAddress = "EMAILADDRESS",
  nationalIdentityNumber = "NATIONALIDENTITYNUMBER",
  isbn = "ISBN",
  issn = "ISSN",
  lisSourcedId = "LISSOURCEDID",
  oneRosterSourcedId = "ONEROSTERSOURCEDID",
  sisSourcedId = "SISSOURCEDID",
  ltiContextId = "LTICONTEXTID",
  ltiDeploymentId = "LTIDEPLOYMENTID",
  ltiToolId = "LTITOOLID",
  ltiPlatformId = "LTIPLATFORMID",
  ltiUserId = "LTIUSERID",
  identifier = "IDENTIFIER",
}
